Rvfbrnet 36
Social-projects-Rivne/medical_doc_managment pull request #3
Opened 2017-03-16 13:28 UTC by AndriyKatsubo

2017-03-16 20:54 UTC, Ravennod submitted a review, later dismissed
I have left two comments related to IsActive field.

2017-03-16 20:54 UTC, Ravennod commented on MedicalDocManagment.UI/src/app/views/users.list.html
> +        <th>Чи активний</th>
IsActive field should not be displayed on this page.

2017-03-16 20:54 UTC, Ravennod commented on MedicalDocManagment.UI/src/app/views/users.list.html
> +        <td>{{user.isactive}}</td>
IsActive field should not be displayed on this page.

2017-03-16 20:56 UTC, AndriyKatsubo commented on MedicalDocManagment.UI/src/app/views/users.list.html
> +        <td>{{user.isactive}}</td>
Why not?

2017-03-16 21:03 UTC, AndriyKatsubo commented on MedicalDocManagment.UI/src/app/views/users.list.html
> +        <td>{{user.isactive}}</td>
ok, nevermind

2017-03-16 21:15 UTC, artempanko requested changes

2017-03-16 21:15 UTC, artempanko commented on MedicalDocManagment.UI/src/app/users.list.ts
> +            { username: "Іван", email: "ivan@lala.net", position: "лікар", role: "якась роль", isactive: "так" },
Please use boolean type in property isactive and follow the code convention.

2017-03-16 21:21 UTC, AndriyKatsubo commented on MedicalDocManagment.UI/src/app/users.list.ts
> +            { username: "Іван", email: "ivan@lala.net", position: "лікар", role: "якась роль", isactive: "так" },
Where exactly do you see incompatibility with code convention?

2017-03-16 21:23 UTC, Shooter75 commented
It seems to be ok, but look at the new project structure. It's different. 
Also there are too many useless commits here.

2017-03-16 21:28 UTC, artempanko submitted a review, later dismissed
Follow the code convention.

2017-03-16 21:28 UTC, artempanko commented on MedicalDocManagment.UI/src/app/users.list.ts
> +    users = this.getUsersList();
unused property users

2017-03-16 21:28 UTC, artempanko commented on MedicalDocManagment.UI/src/app/users.list.ts
> +            { username: "Іван", email: "ivan@lala.net", position: "лікар", role: "якась роль", isactive: "так" },
> isactive

2017-03-17 06:09 UTC, AndriyKatsubo commented on MedicalDocManagment.UI/src/app/users.list.ts
> +            { username: "Іван", email: "ivan@lala.net", position: "лікар", role: "якась роль", isactive: "так" },
ok, done.

2017-03-17 10:38 UTC, closed without merging