Hotfix/single ui application
Social-projects-Rivne/medical_doc_managment pull request #65
Opened 2017-04-20 20:32 UTC by Shooter75

-added `.vscode` foldre into `.gitignore`
-marged 3 other UI applications into signle
-changed reference from `/app/core/index.html` to `/app` into `index.html`

Following components doesn't work because of a previous routing.

2017-04-20 20:43 UTC, Shooter75 commented
Commit's names have went wrong because I use GitBash for work with Git and symbols like `.`  and ` are systematic.

2017-04-21 07:29 UTC, AndriyKatsubo commented
I had run the project and default web-page looked as following:
![default](https://cloud.githubusercontent.com/assets/1482684/25267305/dc2e736e-267c-11e7-8173-b0b54d0f8870.png)
I think you should fix this.

2017-04-21 07:38 UTC, AndriiKatsubo requested changes
Changes were requested according to the result of running the project in it's current state.

2017-04-21 07:38 UTC, AndriyKatsubo commented on MedicalDocManagment.WebUI/systemjs.config.js
> +            //main_app: 'app/main',
Consider removing commented.

2017-04-21 07:38 UTC, AndriyKatsubo commented on MedicalDocManagment.WebUI/app/index.html
> +        //System.import('main_app').catch(function (err) { console.error(err); });
Consider removing commented System.import's.

2017-04-21 07:43 UTC, Shooter75 commented
I wish to do it but without routing it's impossible.
Alex, said that he is going to fix routing. After that I be able to fix this layout.

2017-04-21 07:47 UTC, AndriyKatsubo commented
> I wish to do it but without routing it's impossible.
Alex, said that he is going to fix routing. After that I be able to fix this layout.

Ok then.

2017-04-21 07:47 UTC, AndriiKatsubo approved these changes

2017-04-23 19:05 UTC, Ravennod approved these changes

2017-04-23 20:24 UTC, merged