Hotfix/user edit
Social-projects-Rivne/medical_doc_managment pull request #80
Opened 2017-04-27 06:04 UTC by Shooter75

Improved design

![image](https://cloud.githubusercontent.com/assets/13874357/25469923/1161232e-2b28-11e7-8658-4db7f8850cd3.png)
![image](https://cloud.githubusercontent.com/assets/13874357/25469938/240841ce-2b28-11e7-968e-a8a81dbbcfa2.png)

2017-04-27 13:59 UTC, AndriiKatsubo requested changes
Correction of grammar mistakes was requested.

2017-04-27 13:59 UTC, AndriyKatsubo commented on MedicalDocManagment.WebUI/app/components/user/users-list/page/item/item-actionlist/item-actionlist-edit/modal/modal.component.html
> +                        <label for="email">Електнона пошта</label>
"Електронна"

2017-04-28 07:48 UTC, AndriiKatsubo approved these changes

2017-04-28 20:30 UTC, Ravennod approved these changes

2017-04-29 05:46 UTC, merged