Hotfix/ui add patient
Social-projects-Rivne/medical_doc_managment pull request #84
Opened 2017-05-01 18:09 UTC by Shooter75

![screenshot 9](https://cloud.githubusercontent.com/assets/13874357/25588764/61d57502-2eb2-11e7-8b90-ed7b2f4e58b7.png)
![screenshot 10](https://cloud.githubusercontent.com/assets/13874357/25588765/61d67402-2eb2-11e7-9171-d9ad93b754de.png)

2017-05-01 18:35 UTC, AndriiKatsubo submitted a review, later dismissed

2017-05-02 09:26 UTC, Ravennod submitted a review, later dismissed

2017-05-02 18:48 UTC, Ravennod approved these changes

2017-05-02 18:50 UTC, AndriiKatsubo requested changes
Correction of grammar mistake was requested.

2017-05-02 18:50 UTC, AndriyKatsubo commented on MedicalDocManagment.WebUI/app/components/childrens-card/children-cards-list/add/children-card-add.component.html
> +                Поле "Ким направлено" обовёязкове!
обов'язкове.

2017-05-02 18:52 UTC, AndriiKatsubo approved these changes

2017-05-02 18:53 UTC, merged